name: deploy
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install dependencies
        run: npm i --package-lock-only && npm ci

      - name: Build
        run: npm run build

      - name: Zip
        run: zip -r app-remixnestedroutes.zip . -x *.git*

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-remixnestedroutes
          publish-profile: ${{ secrets.AZURE_PUBLISH_SETTINGS  }}
          package: app-remixnestedroutes.zip
