name: deploy
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.workflow }}
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # pnpm使いたかったが、Freeプランでは容量不足になるので断念
      # - name: Setup Node.js
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 8

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip
        run: |
          du -sh .
          zip -rq app-remixnestedroutes.zip . -x *.git*
          du -sh app-remixnestedroutes.zip

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-remixnestedroutes
          publish-profile: ${{ secrets.AZURE_PUBLISH_SETTINGS  }}
          package: app-remixnestedroutes.zip
